namespace HandOfFateAccess.Localization {
	/// <summary>Italian (it) authored-string table. The English source of
	/// truth and the translator notes live in StringTable.</summary>
	internal static class StringTableIt {
		internal static StringTable Create() {
			return new StringTable {
				ScreenLoading = "Caricamento",
				ScreenIntro = "Intro",
				ScreenAttract = "Modalità demo",
				ScreenMainMenu = "Menu principale",
				ScreenDeckBuilder = "Costruzione mazzo",
				ScreenDungeonSelect = "Selezione dungeon",
				ScreenMap = "Mappa",
				ScreenCardTable = "Tavolo delle carte",
				ScreenEncounter = "Incontro",
				ScreenCombat = "Combattimento",
				ScreenShop = "Negozio",
				ScreenDialogue = "Dialogo",
				ScreenInventory = "Inventario",
				ScreenPaused = "In pausa",
				ScreenResults = "Risultati",
				ScreenCabinet = "Vetrina",
				CardCompleted = "completata",
				CardNew = "nuova",
				CardPinned = "non rimovibile",
				CardCharge = "carica",
				CardCharges = "cariche",
				CardLocked = "bloccata",
				DeckInsufficient = "insufficiente",
				DeckTooMany = "troppe",
				ControlContinue = "Continua",
				TokenReward = "gettone ricompensa",
				AddToDeck = "aggiungi al mazzo",
				SlotEmpty = "vuoto",
				CardToken = "gettone disponibile",
				ResourceHealth = "salute",
				ResourceMaxHealth = "salute massima",
				ResourceFood = "cibo",
				ResourceGold = "oro",
				ResourceIronOre = "minerale di ferro",
				ResourceTokens = "gettoni",
				StatusNoRun = "Nessuna partita in corso",
				ProgressScore = "punteggio",
				ScorePlus = "più",
				ScoreTimes = "per",
				ShopInsufficient = "oro insufficiente",
				ZoomReplacing = "sostituisce",
				CardFaceDown = "carta coperta",
				MapSlotAttached = "con",
				MapCellHere = "qui",
				MapCellReachable = "raggiungibile",
				MapCellLocked = "bloccata",
				MapCellOpen = "aperta",
				MapExits = "uscite",
				DirUp = "su",
				DirDown = "giù",
				DirLeft = "sinistra",
				DirRight = "destra",
				MapRevealed = "rivelata",
				SliderPercentFormat = "{0}%",
				BindingPressKey = "premi un tasto",
				BindingConflict = "conflitto",
				GambitSlotFormat = "Slot {0}",
				GlossaryTitle = "Glossario dei suoni",
				GlossaryClosed = "Glossario chiuso",
				GlossaryBlock = "Parata, attacco che puoi parare, o riflettere se a distanza",
				GlossaryDodge = "Schivata, attacco da schivare, anche il lancio di un pericolo",
				GlossaryProjectile = "Proiettile, colpo in volo",
				GlossaryProjectileReflected = "Proiettile riflesso, il tuo colpo che torna verso un nemico",
				GlossaryZonePrimed = "Zona innescata, trappola in attesa, avvicinarsi la attiva",
				GlossaryZoneArming = "Zona in attivazione, pericolo in formazione, danno non ancora attivo",
				GlossaryZoneActive = "Zona attiva, area che fa danno a starci dentro",
				GlossaryZoneInside = "Zona dentro, sei in un pericolo, allontanati dal suono",
				GlossaryWallTones = "Toni muro, muri a destra, a sinistra, in alto, in basso",
				GlossaryWallCollision = "Collisione muro, hai urtato un muro",
				GlossaryEnemyPing = "Ping nemico, nemico più vicino, risponde al tasto localizzatore",
				GlossaryChest = "Segnale forziere, un forziere oppure oro o cibo a terra, raggiungilo per raccogliere",
				GlossaryExit = "Segnale uscita, raggiungilo per completare il livello, termina anche uno scontro col boss",
				GlossaryRecharge = "Ricarica, un'abilità di arma o artefatto è di nuovo pronta, arma a sinistra, artefatto a destra",
				PluginLoadedFormat = "Hand of Fate Accesso versione {0} caricato"
			};
		}
	}
}
