namespace HandOfFateAccess.Localization {
	/// <summary>French (fr) authored-string table. The English source of
	/// truth and the translator notes live in StringTable.</summary>
	internal static class StringTableFr {
		internal static StringTable Create() {
			return new StringTable {
				ScreenLoading = "Chargement",
				ScreenIntro = "Intro",
				ScreenAttract = "Veille",
				ScreenMainMenu = "Menu principal",
				ScreenDeckBuilder = "Éditeur de deck",
				ScreenDungeonSelect = "Sélection du donjon",
				ScreenMap = "Carte",
				ScreenCardTable = "Table de jeu",
				ScreenEncounter = "Rencontre",
				ScreenCombat = "Combat",
				ScreenShop = "Boutique",
				ScreenDialogue = "Dialogue",
				ScreenInventory = "Inventaire",
				ScreenPaused = "En pause",
				ScreenResults = "Résultats",
				ScreenCabinet = "Cabinet",
				CardCompleted = "terminé",
				CardNew = "nouveau",
				CardPinned = "retrait impossible",
				CardCharge = "charge",
				CardCharges = "charges",
				CardLocked = "verrouillé",
				DeckInsufficient = "insuffisant",
				DeckTooMany = "en trop",
				ControlContinue = "Continuer",
				TokenReward = "jeton de récompense",
				AddToDeck = "ajouter au deck",
				SlotEmpty = "vide",
				CardToken = "jeton disponible",
				ResourceHealth = "vie",
				ResourceMaxHealth = "vie max",
				ResourceFood = "nourriture",
				ResourceGold = "or",
				ResourceIronOre = "minerai de fer",
				ResourceTokens = "jetons",
				StatusNoRun = "Aucune partie en cours",
				ProgressScore = "score",
				ScorePlus = "plus",
				ScoreTimes = "fois",
				ShopInsufficient = "or insuffisant",
				ZoomReplacing = "remplace",
				CardFaceDown = "carte face cachée",
				MapSlotAttached = "avec",
				MapCellHere = "ici",
				MapCellReachable = "accessible",
				MapCellLocked = "verrouillé",
				MapCellOpen = "ouvert",
				MapExits = "sorties",
				DirUp = "haut",
				DirDown = "bas",
				DirLeft = "gauche",
				DirRight = "droite",
				MapRevealed = "révélé",
				SliderPercentFormat = "{0}%",
				BindingPressKey = "appuyez sur une touche",
				BindingConflict = "conflit",
				GambitSlotFormat = "Position {0}",
				GlossaryTitle = "Glossaire des sons",
				GlossaryClosed = "Glossaire fermé",
				GlossaryBlock = "Contrer, attaque que vous pouvez contrer, ou renvoyer si à distance",
				GlossaryDodge = "Éviter, attaque que vous devez éviter, aussi le lancement d'un danger",
				GlossaryProjectile = "Projectile, tir en vol",
				GlossaryProjectileReflected = "Projectile renvoyé, votre tir qui repart vers un ennemi",
				GlossaryZonePrimed = "Zone amorcée, piège en attente, s'en approcher le déclenche",
				GlossaryZoneArming = "Zone en armement, danger présent mais dégâts inactifs, à plein volume vous êtes dessus",
				GlossaryZoneActive = "Zone active, surface qui blesse tant qu'on y reste",
				GlossaryZoneInside = "Zone, intérieur, vous êtes dans un danger actif, éloignez-vous du son",
				GlossaryWallTones = "Tonalités de mur, murs droite, gauche, haut, bas",
				GlossaryWallCollision = "Collision murale, vous avez heurté un mur",
				GlossaryEnemyPing = "Ping ennemi, ennemi le plus proche, répond à la touche de localisation",
				GlossaryChest = "Balise de coffre, un coffre ou de l'or ou de la nourriture au sol, rejoignez-la pour ramasser, dans les salles de pièges elle répond à la touche de localisation",
				GlossaryExit = "Balise de sortie, rejoignez-la pour finir le niveau, termine aussi un combat de boss",
				GlossaryRecharge = "Recharge, une capacité d'arme ou d'artefact est de nouveau prête, arme à gauche, artefact à droite",
				PluginLoadedFormat = "Hand of Fate Accès version {0} chargé",
			};
		}
	}
}
