namespace HandOfFateAccess.Localization {
	/// <summary>Brazilian Portuguese (pt-br) authored-string table. The English
	/// source of truth and the translator notes live in StringTable.</summary>
	internal static class StringTablePtBr {
		internal static StringTable Create() {
			return new StringTable {
				ScreenLoading = "Carregando",
				ScreenIntro = "Introdução",
				ScreenAttract = "Demonstração",
				ScreenMainMenu = "Menu principal",
				ScreenDeckBuilder = "Construtor de baralho",
				ScreenDungeonSelect = "Seleção de masmorra",
				ScreenMap = "Mapa",
				ScreenCardTable = "Mesa de cartas",
				ScreenEncounter = "Encontro",
				ScreenCombat = "Combate",
				ScreenShop = "Loja",
				ScreenDialogue = "Diálogo",
				ScreenInventory = "Inventário",
				ScreenPaused = "Pausado",
				ScreenResults = "Resultados",
				ScreenCabinet = "Gabinete",
				CardCompleted = "concluída",
				CardNew = "nova",
				CardPinned = "não pode ser removida",
				CardCharge = "carga",
				CardCharges = "cargas",
				CardLocked = "bloqueada",
				DeckInsufficient = "insuficiente",
				DeckTooMany = "em excesso",
				ControlContinue = "Continuar",
				TokenReward = "ficha de recompensa",
				AddToDeck = "adicionar ao baralho",
				SlotEmpty = "vazio",
				CardToken = "ficha disponível",
				ResourceHealth = "vida",
				ResourceMaxHealth = "vida máxima",
				ResourceFood = "comida",
				ResourceGold = "ouro",
				ResourceIronOre = "minério de ferro",
				ResourceTokens = "fichas",
				StatusNoRun = "Sem partida em andamento",
				ProgressScore = "pontos",
				ScorePlus = "mais",
				ScoreTimes = "vezes",
				ShopInsufficient = "ouro insuficiente",
				ZoomReplacing = "substituindo",
				CardFaceDown = "carta virada para baixo",
				MapSlotAttached = "com",
				MapCellHere = "aqui",
				MapCellReachable = "alcançável",
				MapCellLocked = "bloqueada",
				MapCellOpen = "aberta",
				MapExits = "saídas",
				DirUp = "para cima",
				DirDown = "para baixo",
				DirLeft = "esquerda",
				DirRight = "direita",
				MapRevealed = "revelada",
				SliderPercentFormat = "{0}%",
				BindingPressKey = "pressione uma tecla",
				BindingConflict = "conflito",
				GambitSlotFormat = "Posição {0}",
				GlossaryTitle = "Glossário de sons",
				GlossaryClosed = "Glossário fechado",
				GlossaryBlock = "Bloqueio, ataque que você pode bloquear, ou refletir se for à distância",
				GlossaryDodge = "Evadir, ataque que você deve evadir, também um perigo sendo lançado",
				GlossaryProjectile = "Projétil, tiro em voo",
				GlossaryProjectileReflected = "Projétil refletido, seu tiro voando de volta contra um inimigo",
				GlossaryZonePrimed = "Zona engatilhada, armadilha em espera, aproximar-se a dispara",
				GlossaryZoneArming = "Zona armando, perigo se formando, dano ainda não ativo",
				GlossaryZoneActive = "Zona ativa, área que causa dano ao ficar dentro",
				GlossaryZoneInside = "Dentro da zona, você está em um perigo, afaste-se do som",
				GlossaryWallTones = "Tons de parede, paredes à direita, à esquerda, acima, abaixo",
				GlossaryWallCollision = "Colisão com parede, você andou contra uma parede",
				GlossaryEnemyPing = "Ping de inimigo, inimigo mais próximo, responde à tecla localizadora",
				GlossaryChest = "Sinal de baú, um baú ou ouro ou comida no chão, caminhe até ele para coletar",
				GlossaryExit = "Sinal de saída, caminhe até ele para terminar a estância, também encerra uma luta de chefe",
				GlossaryRecharge = "Recarga, uma habilidade de arma ou artefato está pronta de novo, arma à esquerda, artefato à direita",
				PluginLoadedFormat = "Hand of Fate Acesso versão {0} carregado",
			};
		}
	}
}
