namespace HandOfFateAccess.Localization {
	/// <summary>Simplified Chinese (zh) authored-string table. The English source
	/// of truth and the translator notes live in StringTable.</summary>
	internal static class StringTableZh {
		internal static StringTable Create() {
			return new StringTable {
				ScreenLoading = "加载中",
				ScreenIntro = "开场",
				ScreenAttract = "待机画面",
				ScreenMainMenu = "主菜单",
				ScreenDeckBuilder = "牌组构筑",
				ScreenDungeonSelect = "地下城选择",
				ScreenMap = "地图",
				ScreenCardTable = "牌桌",
				ScreenEncounter = "遭遇",
				ScreenCombat = "作战",
				ScreenShop = "商店",
				ScreenDialogue = "对话框",
				ScreenInventory = "清单",
				ScreenPaused = "暂停",
				ScreenResults = "结算",
				ScreenCabinet = "陈列柜",
				CardCompleted = "已完成",
				CardNew = "新卡",
				CardPinned = "不可移除",
				CardCharge = "次充能",
				CardCharges = "次充能",
				CardLocked = "未解锁",
				DeckInsufficient = "不足",
				DeckTooMany = "过多",
				ControlContinue = "继续",
				TokenReward = "奖励令牌",
				AddToDeck = "添加到牌组",
				SlotEmpty = "空",
				CardToken = "可获得令牌",
				ResourceHealth = "生命值",
				ResourceMaxHealth = "最大生命值",
				ResourceFood = "食物",
				ResourceGold = "金币",
				ResourceIronOre = "铁矿石",
				ResourceTokens = "令牌",
				StatusNoRun = "没有进行中的冒险",
				ProgressScore = "分",
				ScorePlus = "加",
				ScoreTimes = "乘以",
				ShopInsufficient = "金币不足",
				ZoomReplacing = "替换",
				CardFaceDown = "未翻开的卡牌",
				MapSlotAttached = "附带",
				MapCellHere = "当前位置",
				MapCellReachable = "可前往",
				MapCellLocked = "未解锁",
				MapCellOpen = "已解锁",
				MapExits = "出口",
				DirUp = "上",
				DirDown = "下",
				DirLeft = "左",
				DirRight = "右",
				MapRevealed = "翻开",
				SliderPercentFormat = "{0}%",
				BindingPressKey = "按一个键",
				BindingConflict = "冲突",
				GambitSlotFormat = "第{0}格",
				GlossaryTitle = "音效说明",
				GlossaryClosed = "音效说明已关闭",
				GlossaryBlock = "格挡，可格挡的攻击，远程则可反弹",
				GlossaryDodge = "闪避，必须闪避的攻击，也表示危险物发射",
				GlossaryProjectile = "投射物，飞行中的远程攻击",
				GlossaryProjectileReflected = "反弹投射物，被你反弹、正飞向敌人的攻击",
				GlossaryZonePrimed = "区域待触发，陷阱待机中，靠近会触发",
				GlossaryZoneArming = "区域形成中，危险正在形成，尚未造成伤害",
				GlossaryZoneActive = "区域激活，站在里面会受伤",
				GlossaryZoneInside = "区域之内，你在危险区域中，向远离声音的方向移动",
				GlossaryWallTones = "墙壁音，墙在右、左、上、下",
				GlossaryWallCollision = "墙壁碰撞，撞到了墙",
				GlossaryEnemyPing = "敌人定位音，最近的敌人，响应定位键",
				GlossaryChest = "宝箱信标，走过去打开宝箱",
				GlossaryExit = "出口信标，走过去完成关卡，也可结束首领战",
				PluginLoadedFormat = "命运之手无障碍，版本 {0} 已加载",
			};
		}
	}
}
