namespace HandOfFateAccess.Localization {
	/// <summary>Russian (ru) authored-string table. The English source of
	/// truth and the translator notes live in StringTable.</summary>
	internal static class StringTableRu {
		internal static StringTable Create() {
			return new StringTable {
				ScreenLoading = "Загрузка",
				ScreenIntro = "Вступление",
				ScreenAttract = "Заставка",
				ScreenMainMenu = "Главное меню",
				ScreenDeckBuilder = "Редактор колоды",
				ScreenDungeonSelect = "Выбор подземелья",
				ScreenMap = "План",
				ScreenCardTable = "Карточный стол",
				ScreenEncounter = "Встреча",
				ScreenCombat = "Бой",
				ScreenShop = "Лавка",
				ScreenDialogue = "Диалог",
				ScreenInventory = "Инвентарь",
				ScreenPaused = "Пауза",
				ScreenResults = "Результаты",
				ScreenCabinet = "Витрина",
				CardCompleted = "завершено",
				CardNew = "новая",
				CardPinned = "нельзя удалить",
				CardCharge = "заряд",
				CardCharges = "заряда",
				CardLocked = "заблокировано",
				DeckInsufficient = "недостаточно",
				DeckTooMany = "слишком много",
				ControlContinue = "Продолжить",
				TokenReward = "наградная фишка",
				AddToDeck = "добавить в колоду",
				SlotEmpty = "пусто",
				CardToken = "есть фишка",
				ResourceHealth = "здоровья",
				ResourceMaxHealth = "макс. здоровья",
				ResourceFood = "пищи",
				ResourceGold = "золота",
				ResourceIronOre = "железной руды",
				ResourceTokens = "фишек",
				StatusNoRun = "Нет активного забега",
				ProgressScore = "счет",
				ScorePlus = "плюс",
				ScoreTimes = "умножить на",
				ShopInsufficient = "недостаточно золота",
				ZoomReplacing = "заменяет",
				CardFaceDown = "закрытая карта",
				MapSlotAttached = "плюс",
				MapCellHere = "здесь",
				MapCellReachable = "доступно",
				MapCellLocked = "заблокировано",
				MapCellOpen = "открыто",
				MapExits = "выходы",
				DirUp = "вверх",
				DirDown = "вниз",
				DirLeft = "налево",
				DirRight = "направо",
				MapRevealed = "раскрыто",
				SliderPercentFormat = "{0}%",
				BindingPressKey = "нажмите клавишу",
				BindingConflict = "конфликт",
				GambitSlotFormat = "Слот {0}",
				GlossaryTitle = "Глоссарий звуков",
				GlossaryClosed = "Глоссарий закрыт",
				GlossaryBlock = "Блок, атака, которую можно блокировать, или отразить, если дальняя",
				GlossaryDodge = "Уклонение, атака, от которой нужно уклониться, также запуск опасности",
				GlossaryProjectile = "Снаряд, выстрел в полете",
				GlossaryProjectileReflected = "Отраженный снаряд, ваш выстрел летит обратно во врага",
				GlossaryZonePrimed = "Зона взведена, ловушка ждет, срабатывает при приближении",
				GlossaryZoneArming = "Зона формируется, опасность возникает, урона еще нет",
				GlossaryZoneActive = "Зона активна, область наносит урон, если стоять в ней",
				GlossaryZoneInside = "Внутри зоны, вы в опасной области, уходите от звука",
				GlossaryWallTones = "Тоны стен, стены справа, слева, сверху, снизу",
				GlossaryWallCollision = "Столкновение со стеной, вы врезались в стену",
				GlossaryEnemyPing = "Пинг врага, ближайший враг, отвечает на клавишу локатора",
				GlossaryChest = "Маяк сундука, сундук или лежащие золото или еда, подойдите, чтобы подобрать, в комнатах с ловушками отвечает на клавишу локатора",
				GlossaryExit = "Маяк выхода, подойдите к нему, чтобы завершить уровень, также заканчивает бой с боссом",
				GlossaryRecharge = "Перезарядка, способность оружия или артефакта снова готова, оружие слева, артефакт справа",
				PluginLoadedFormat = "Hand of Fate Доступ версии {0} загружен",
			};
		}
	}
}
