namespace HandOfFateAccess.Localization {
	/// <summary>Japanese (ja) authored-string table. The English source of
	/// truth and the translator notes live in StringTable.</summary>
	internal static class StringTableJa {
		internal static StringTable Create() {
			return new StringTable {
				ScreenLoading = "ロード中",
				ScreenIntro = "イントロ",
				ScreenAttract = "デモ画面",
				ScreenMainMenu = "メインメニュー",
				ScreenDeckBuilder = "デッキビルダー",
				ScreenDungeonSelect = "ダンジョン選択",
				ScreenMap = "地図",
				ScreenCardTable = "カードテーブル",
				ScreenEncounter = "エンカウンター",
				ScreenCombat = "戦闘",
				ScreenShop = "店",
				ScreenDialogue = "ダイアログ",
				ScreenInventory = "インベントリー",
				ScreenPaused = "ポーズ",
				ScreenResults = "リザルト",
				ScreenCabinet = "キャビネット",
				CardCompleted = "完了",
				CardNew = "新規",
				CardPinned = "削除不可",
				CardCharge = "回",
				CardCharges = "回",
				CardLocked = "ロック中",
				DeckInsufficient = "不足",
				DeckTooMany = "超過",
				ControlContinue = "続ける",
				TokenReward = "報酬トークン",
				AddToDeck = "デッキに追加",
				SlotEmpty = "空き",
				CardToken = "トークン獲得可能",
				ResourceHealth = "ヘルス",
				ResourceMaxHealth = "マックスヘルス",
				ResourceFood = "フード",
				ResourceGold = "ゴールド",
				ResourceIronOre = "鉄鉱石",
				ResourceTokens = "トークン",
				StatusNoRun = "進行中のランなし",
				ProgressScore = "スコア",
				ScorePlus = "プラス",
				ScoreTimes = "かける",
				ShopInsufficient = "ゴールドが不足",
				ZoomReplacing = "交換対象",
				CardFaceDown = "裏向きのカード",
				MapSlotAttached = "付属",
				MapCellHere = "現在地",
				MapCellReachable = "移動可能",
				MapCellLocked = "ロック中",
				MapCellOpen = "開放",
				MapExits = "接続",
				DirUp = "上",
				DirDown = "下",
				DirLeft = "左",
				DirRight = "右",
				MapRevealed = "公開",
				SliderPercentFormat = "{0}%",
				BindingPressKey = "キー入力待ち",
				BindingConflict = "競合",
				GambitSlotFormat = "スロット{0}",
				GlossaryTitle = "サウンド用語集",
				GlossaryClosed = "用語集を閉じた",
				GlossaryBlock = "ブロック、ブロックできる攻撃、遠距離なら反射できる",
				GlossaryDodge = "避ける、避けるしかない攻撃、ハザード発射時にも鳴る",
				GlossaryProjectile = "飛翔体、飛行中の弾",
				GlossaryProjectileReflected = "反射飛翔体、自分が反射した弾が敵へ飛んでいる",
				GlossaryZonePrimed = "ゾーン待機、休止中の罠、近づくと発動",
				GlossaryZoneArming = "ゾーン形成、ハザードが形成中、まだダメージなし",
				GlossaryZoneActive = "ゾーン作動、中に立つとダメージを受ける範囲",
				GlossaryZoneInside = "ゾーン内部、ハザードの中にいる、音から離れる方向へ移動",
				GlossaryWallTones = "壁トーン、壁が右、左、上、下",
				GlossaryWallCollision = "壁衝突、壁にぶつかった",
				GlossaryEnemyPing = "敵ピング、最寄りの敵、ロケーターキーに応答",
				GlossaryChest = "宝箱ビーコン、そこまで歩くと宝箱が開く",
				GlossaryExit = "出口ビーコン、そこまで歩くとレベル終了、ボス戦も終わる",
				PluginLoadedFormat = "ハンドオブフェイト・アクセス バージョン{0} 読み込み完了"
			};
		}
	}
}
