namespace HandOfFateAccess.Localization {
	/// <summary>Hungarian (hu) authored-string table. The English source of
	/// truth and the translator notes live in StringTable.</summary>
	internal static class StringTableHu {
		internal static StringTable Create() {
			return new StringTable {
				ScreenLoading = "Betöltés",
				ScreenIntro = "Intró",
				ScreenAttract = "Demó",
				ScreenMainMenu = "Főmenü",
				ScreenDeckBuilder = "Pakliszerkesztő",
				ScreenDungeonSelect = "Kalandválasztás",
				ScreenMap = "Térkép",
				ScreenCardTable = "Kártyaasztal",
				ScreenEncounter = "Találkozás",
				ScreenCombat = "Harc",
				ScreenShop = "Bolt",
				ScreenDialogue = "Párbeszédablak",
				ScreenInventory = "Leltár",
				ScreenPaused = "Szüneteltetve",
				ScreenResults = "Eredmények",
				ScreenCabinet = "Vitrin",
				CardCompleted = "teljesítve",
				CardNew = "új",
				CardPinned = "nem távolítható el",
				CardCharge = "töltet",
				CardCharges = "töltet",
				CardLocked = "zárva",
				DeckInsufficient = "nem elegendő",
				DeckTooMany = "túl sok",
				ControlContinue = "Folytatás",
				TokenReward = "jutalomzseton",
				AddToDeck = "hozzáadás a paklihoz",
				SlotEmpty = "üres",
				CardToken = "zseton nyerhető",
				ResourceHealth = "életerő",
				ResourceMaxHealth = "max életerő",
				ResourceFood = "étel",
				ResourceGold = "arany",
				ResourceIronOre = "vasérc",
				ResourceTokens = "zseton",
				StatusNoRun = "Nincs aktív kaland",
				ProgressScore = "pont",
				ScorePlus = "plusz",
				ScoreTimes = "szorozva",
				ShopInsufficient = "nem elegendő arany",
				ZoomReplacing = "lecseréli",
				CardFaceDown = "lefordított kártya",
				MapSlotAttached = "alatta",
				MapCellHere = "itt",
				MapCellReachable = "elérhető",
				MapCellLocked = "zárva",
				MapCellOpen = "nyitva",
				MapExits = "kijáratok",
				DirUp = "fel",
				DirDown = "le",
				DirLeft = "balra",
				DirRight = "jobbra",
				MapRevealed = "felfedve",
				SliderPercentFormat = "{0}%",
				BindingPressKey = "nyomj meg egy billentyűt",
				BindingConflict = "ütközés",
				GambitSlotFormat = "{0}. hely",
				GlossaryTitle = "Hangszótár",
				GlossaryClosed = "Hangszótár bezárva",
				GlossaryBlock = "Hárítás, hárítható támadás, ha távolsági, visszaverhető",
				GlossaryDodge = "Kitérés, támadás, ami elől ki kell térned, valamint induló veszély is",
				GlossaryProjectile = "Lövedék, lövés repülés közben",
				GlossaryProjectileReflected = "Visszavert lövedék, a lövésed repül vissza egy ellenség felé",
				GlossaryZonePrimed = "Zóna élesítve, nyugvó csapda, közeledésre elsül",
				GlossaryZoneArming = "Zóna élesedik, veszély formálódik, még nem sebez",
				GlossaryZoneActive = "Zóna aktív, terület, amelyben állni sebez",
				GlossaryZoneInside = "Zónán belül, veszélyzónában vagy, távolodj a hangtól",
				GlossaryWallTones = "Falhangok, falak jobbra, balra, fent, lent",
				GlossaryWallCollision = "Falütközés, falnak mentél",
				GlossaryEnemyPing = "Ellenségjelzés, a legközelebbi ellenség, a keresőgombra válaszol",
				GlossaryChest = "Ládajelző, sétálj oda a láda kinyitásához",
				GlossaryExit = "Kijáratjelző, sétálj oda a szint befejezéséhez, a főellenség elleni harcot is lezárja",
				GlossaryRecharge = "Újratöltés, egy fegyver- vagy ereklyeképesség újra használható, fegyver balra, ereklye jobbra",
				PluginLoadedFormat = "Hand of Fate Hozzáférés {0} verzió betöltve",
			};
		}
	}
}
