namespace HandOfFateAccess.Localization {
	/// <summary>Ukrainian (uk) authored-string table. The English source of
	/// truth and the translator notes live in StringTable.</summary>
	internal static class StringTableUk {
		internal static StringTable Create() {
			return new StringTable {
				ScreenLoading = "Завантаження",
				ScreenIntro = "Вступ",
				ScreenAttract = "Заставка",
				ScreenMainMenu = "Головне меню",
				ScreenDeckBuilder = "Конструктор колоди",
				ScreenDungeonSelect = "Вибір підземелля",
				ScreenMap = "Мапа",
				ScreenCardTable = "Картковий стіл",
				ScreenEncounter = "Зустріч",
				ScreenCombat = "Бій",
				ScreenShop = "Крамниця",
				ScreenDialogue = "Діалог",
				ScreenInventory = "Інвентар",
				ScreenPaused = "Пауза",
				ScreenResults = "Результати",
				ScreenCabinet = "Вітрина",
				CardCompleted = "завершено",
				CardNew = "нова",
				CardPinned = "не можна вилучити",
				CardCharge = "заряд",
				CardCharges = "заряди",
				CardLocked = "заблоковано",
				DeckInsufficient = "недостатньо",
				DeckTooMany = "забагато",
				ControlContinue = "Продовжити",
				TokenReward = "значок нагороди",
				AddToDeck = "додати до колоди",
				SlotEmpty = "порожньо",
				CardToken = "значок доступний",
				ResourceHealth = "здоров'я",
				ResourceMaxHealth = "максимального здоров'я",
				ResourceFood = "їжі",
				ResourceGold = "золота",
				ResourceIronOre = "залізної руди",
				ResourceTokens = "значків",
				StatusNoRun = "Немає активного забігу",
				ProgressScore = "очок",
				ScorePlus = "плюс",
				ScoreTimes = "множник",
				ShopInsufficient = "недостатньо золота",
				ZoomReplacing = "замінює",
				CardFaceDown = "закрита карта",
				MapSlotAttached = "додатково",
				MapCellHere = "тут",
				MapCellReachable = "досяжно",
				MapCellLocked = "заблоковано",
				MapCellOpen = "відкрито",
				MapExits = "виходи",
				DirUp = "вгору",
				DirDown = "вниз",
				DirLeft = "ліворуч",
				DirRight = "праворуч",
				MapRevealed = "розкрито",
				SliderPercentFormat = "{0}%",
				BindingPressKey = "натисніть клавішу",
				BindingConflict = "конфлікт",
				GambitSlotFormat = "Слот {0}",
				GlossaryTitle = "Глосарій звуків",
				GlossaryClosed = "Глосарій закрито",
				GlossaryBlock = "Блок, атака, яку можна заблокувати, або відбити, якщо дальня",
				GlossaryDodge = "Ухилення, атака, від якої треба ухилитися, також запуск небезпеки",
				GlossaryProjectile = "Снаряд, постріл у польоті",
				GlossaryProjectileReflected = "Відбитий снаряд, ваш постріл летить назад у ворога",
				GlossaryZonePrimed = "Зона напоготові, неактивна пастка, спрацьовує при наближенні",
				GlossaryZoneArming = "Зона озброюється, небезпека є, але шкода вимкнена, на повній гучності ви стоїте на ній",
				GlossaryZoneActive = "Зона активна, ділянка завдає шкоди, якщо стояти в ній",
				GlossaryZoneInside = "Зона всередині, ви в активній небезпечній ділянці, рухайтеся геть від звуку",
				GlossaryWallTones = "Тони стін, стіни праворуч, ліворуч, зверху, знизу",
				GlossaryWallCollision = "Зіткнення зі стіною, ви врізалися в стіну",
				GlossaryEnemyPing = "Пінг ворога, найближчий ворог, відповідає на клавішу локатора",
				GlossaryChest = "Маяк скрині, скриня або золото чи їжа на землі, підійдіть, щоб підібрати, у кімнатах з пастками відповідає на клавішу локатора",
				GlossaryExit = "Маяк виходу, підійдіть до нього, щоб завершити рівень, також завершує бій з босом",
				GlossaryRecharge = "Перезарядка, здібність зброї або артефакта знову готова, зброя ліворуч, артефакт праворуч",
				PluginLoadedFormat = "Hand of Fate Доступ версії {0} завантажено",
			};
		}
	}
}
