namespace HandOfFateAccess.Localization {
	/// <summary>Spanish (es) authored-string table. The English source of
	/// truth and the translator notes live in StringTable.</summary>
	internal static class StringTableEs {
		internal static StringTable Create() {
			return new StringTable {
				ScreenLoading = "Cargando",
				ScreenIntro = "Intro",
				ScreenAttract = "Demostración",
				ScreenMainMenu = "Menú principal",
				ScreenDeckBuilder = "Constructor de baraja",
				ScreenDungeonSelect = "Selección de mazmorra",
				ScreenMap = "Mapa",
				ScreenCardTable = "Mesa de cartas",
				ScreenEncounter = "Encuentro",
				ScreenCombat = "Combate",
				ScreenShop = "Tienda",
				ScreenDialogue = "Diálogo",
				ScreenInventory = "Inventario",
				ScreenPaused = "Pausado",
				ScreenResults = "Resultados",
				ScreenCabinet = "Gabinete",
				CardCompleted = "completada",
				CardNew = "nueva",
				CardPinned = "no se puede eliminar",
				CardCharge = "carga",
				CardCharges = "cargas",
				CardLocked = "bloqueada",
				DeckInsufficient = "insuficiente",
				DeckTooMany = "demasiadas",
				ControlContinue = "Continuar",
				TokenReward = "token de recompensa",
				AddToDeck = "añadir a la baraja",
				SlotEmpty = "vacío",
				CardToken = "token disponible",
				ResourceHealth = "salud",
				ResourceMaxHealth = "salud máxima",
				ResourceFood = "comida",
				ResourceGold = "oro",
				ResourceIronOre = "material de hierro",
				ResourceTokens = "tokens",
				StatusNoRun = "No hay partida en curso",
				ProgressScore = "puntuación",
				ScorePlus = "más",
				ScoreTimes = "por",
				ShopInsufficient = "oro insuficiente",
				ZoomReplacing = "reemplaza a",
				CardFaceDown = "carta boca abajo",
				MapSlotAttached = "con",
				MapCellHere = "aquí",
				MapCellReachable = "alcanzable",
				MapCellLocked = "bloqueada",
				MapCellOpen = "abierta",
				MapExits = "salidas",
				DirUp = "arriba",
				DirDown = "abajo",
				DirLeft = "izquierda",
				DirRight = "derecha",
				MapRevealed = "revelada",
				SliderPercentFormat = "{0}%",
				BindingPressKey = "pulsa una tecla",
				BindingConflict = "conflicto",
				GambitSlotFormat = "Posición {0}",
				GlossaryTitle = "Glosario de sonidos",
				GlossaryClosed = "Glosario cerrado",
				GlossaryBlock = "Bloqueo, ataque que puedes bloquear, o reflejar si es a distancia",
				GlossaryDodge = "Esquivar, ataque que debes esquivar, también un peligro que se lanza",
				GlossaryProjectile = "Proyectil, disparo en vuelo",
				GlossaryProjectileReflected = "Proyectil reflejado, tu disparo volando de vuelta hacia un enemigo",
				GlossaryZonePrimed = "Zona preparada, trampa a la espera, acercarse la dispara",
				GlossaryZoneArming = "Zona armándose, peligro presente pero sin daño, a volumen máximo estás encima",
				GlossaryZoneActive = "Zona activa, área que daña al permanecer dentro",
				GlossaryZoneInside = "Zona dentro, estás en un peligro activo, aléjate del sonido",
				GlossaryWallTones = "Tonos de pared, paredes derecha, izquierda, arriba, abajo",
				GlossaryWallCollision = "Colisión con pared, has chocado contra una pared",
				GlossaryEnemyPing = "Ping de enemigo, enemigo más cercano, responde a la tecla localizadora",
				GlossaryChest = "Baliza de cofre, un cofre u oro o comida en el suelo, camina hacia ella para recogerlo, en salas de trampas responde a la tecla localizadora",
				GlossaryExit = "Baliza de salida, camina hacia ella para terminar el nivel, también termina el combate de jefe",
				GlossaryRecharge = "Recarga, una habilidad de arma o artefacto está lista de nuevo, arma a la izquierda, artefacto a la derecha",
				PluginLoadedFormat = "Hand of Fate Acceso versión {0} cargado"
			};
		}
	}
}
