namespace HandOfFateAccess.Localization {
	/// <summary>Korean (ko) authored-string table. The English source of
	/// truth and the translator notes live in StringTable.</summary>
	internal static class StringTableKo {
		internal static StringTable Create() {
			return new StringTable {
				ScreenLoading = "로딩 중",
				ScreenIntro = "인트로",
				ScreenAttract = "대기 화면",
				ScreenMainMenu = "메인 메뉴",
				ScreenDeckBuilder = "덱 빌더",
				ScreenDungeonSelect = "던전 선택",
				ScreenMap = "맵",
				ScreenCardTable = "카드 테이블",
				ScreenEncounter = "조우",
				ScreenCombat = "전투",
				ScreenShop = "상점",
				ScreenDialogue = "대화 상자",
				ScreenInventory = "인벤토리",
				ScreenPaused = "일시 정지됨",
				ScreenResults = "결과",
				ScreenCabinet = "캐비닛",
				CardCompleted = "완료",
				CardNew = "신규",
				CardPinned = "제거 불가",
				CardCharge = "회 충전",
				CardCharges = "회 충전",
				CardLocked = "잠김",
				DeckInsufficient = "부족함",
				DeckTooMany = "초과",
				ControlContinue = "계속",
				TokenReward = "보상 토큰",
				AddToDeck = "덱에 추가",
				SlotEmpty = "비어 있음",
				CardToken = "토큰 획득 가능",
				ResourceHealth = "체력",
				ResourceMaxHealth = "최대 체력",
				ResourceFood = "음식",
				ResourceGold = "골드",
				ResourceIronOre = "철광석",
				ResourceTokens = "토큰",
				StatusNoRun = "진행 중인 런 없음",
				ProgressScore = "스코어",
				ScorePlus = "플러스",
				ScoreTimes = "곱하기",
				ShopInsufficient = "골드 부족",
				ZoomReplacing = "교체 대상",
				CardFaceDown = "뒷면 카드",
				MapSlotAttached = "동반",
				MapCellHere = "현재 위치",
				MapCellReachable = "이동 가능",
				MapCellLocked = "잠김",
				MapCellOpen = "열림",
				MapExits = "출구",
				DirUp = "위",
				DirDown = "아래",
				DirLeft = "왼쪽",
				DirRight = "오른쪽",
				MapRevealed = "공개",
				SliderPercentFormat = "{0}%",
				BindingPressKey = "키 입력",
				BindingConflict = "충돌",
				GambitSlotFormat = "{0}번 슬롯",
				GlossaryTitle = "소리 용어집",
				GlossaryClosed = "용어집 닫힘",
				GlossaryBlock = "막기, 막을 수 있는 공격, 원거리면 반사 가능",
				GlossaryDodge = "피하기, 반드시 피해야 하는 공격, 위험물 발사 시에도 울림",
				GlossaryProjectile = "투사체, 날아가는 탄환",
				GlossaryProjectileReflected = "반사된 투사체, 적에게 되날아가는 내 탄환",
				GlossaryZonePrimed = "구역 대기, 잠복한 함정, 접근하면 발동",
				GlossaryZoneArming = "구역 준비 중, 위험물 형성 중, 아직 피해 없음",
				GlossaryZoneActive = "구역 활성, 서 있으면 피해를 입는 지역",
				GlossaryZoneInside = "구역 내부, 위험물 안에 있음, 소리 반대쪽으로 이동",
				GlossaryWallTones = "벽 톤, 벽 오른쪽, 왼쪽, 위, 아래",
				GlossaryWallCollision = "벽 충돌, 벽에 부딪힘",
				GlossaryEnemyPing = "적 핑, 가장 가까운 적, 위치 탐지 키에 응답",
				GlossaryChest = "상자 신호음, 걸어가면 상자 열림",
				GlossaryExit = "출구 신호음, 걸어가면 레벨 완료, 보스전도 종료",
				PluginLoadedFormat = "Hand of Fate 액세스 버전 {0} 로드됨"
			};
		}
	}
}
