namespace HandOfFateAccess.Localization {
	/// <summary>German (de) authored-string table. The English source of
	/// truth and the translator notes live in StringTable.</summary>
	internal static class StringTableDe {
		internal static StringTable Create() {
			return new StringTable {
				ScreenLoading = "Lädt",
				ScreenIntro = "Intro",
				ScreenAttract = "Demomodus",
				ScreenMainMenu = "Hauptmenü",
				ScreenDeckBuilder = "Deckbau",
				ScreenDungeonSelect = "Verliesauswahl",
				ScreenMap = "Karte",
				ScreenCardTable = "Kartentisch",
				ScreenEncounter = "Begegnung",
				ScreenCombat = "Kampf",
				ScreenShop = "Laden",
				ScreenDialogue = "Dialog",
				ScreenInventory = "Inventar",
				ScreenPaused = "Pausiert",
				ScreenResults = "Ergebnisse",
				ScreenCabinet = "Vitrine",
				CardCompleted = "abgeschlossen",
				CardNew = "neu",
				CardPinned = "nicht entfernbar",
				CardCharge = "Ladung",
				CardCharges = "Ladungen",
				CardLocked = "gesperrt",
				DeckInsufficient = "nicht genügend",
				DeckTooMany = "zu viele",
				ControlContinue = "Weiter",
				TokenReward = "Belohnungszeichen",
				AddToDeck = "zum Deck hinzufügen",
				SlotEmpty = "leer",
				CardToken = "Zeichen verfügbar",
				ResourceHealth = "Gesundheit",
				ResourceMaxHealth = "max. Gesundheit",
				ResourceFood = "Rationen",
				ResourceGold = "Gold",
				ResourceIronOre = "Eisenerz",
				ResourceTokens = "Zeichen",
				StatusNoRun = "Kein Lauf aktiv",
				ProgressScore = "Punkte",
				ScorePlus = "plus",
				ScoreTimes = "mal",
				ShopInsufficient = "nicht genügend Gold",
				ZoomReplacing = "ersetzt",
				CardFaceDown = "verdeckte Karte",
				MapSlotAttached = "mit",
				MapCellHere = "hier",
				MapCellReachable = "erreichbar",
				MapCellLocked = "gesperrt",
				MapCellOpen = "offen",
				MapExits = "Ausgänge",
				DirUp = "oben",
				DirDown = "unten",
				DirLeft = "links",
				DirRight = "rechts",
				MapRevealed = "aufgedeckt",
				SliderPercentFormat = "{0}%",
				BindingPressKey = "Taste drücken",
				BindingConflict = "Konflikt",
				GambitSlotFormat = "Platz {0}",
				GlossaryTitle = "Klangglossar",
				GlossaryClosed = "Glossar geschlossen",
				GlossaryBlock = "Block, Angriff, den du blocken kannst, bei Fernangriff reflektierbar",
				GlossaryDodge = "Ausweichen, Angriff, dem du ausweichen musst, auch eine startende Gefahr",
				GlossaryProjectile = "Projektil, Geschoss im Flug",
				GlossaryProjectileReflected = "Reflektiertes Projektil, dein Geschoss fliegt zurück auf einen Gegner",
				GlossaryZonePrimed = "Zone bereit, ruhende Falle, Annäherung löst sie aus",
				GlossaryZoneArming = "Zone im Aufbau, Gefahr entsteht, Schaden noch nicht aktiv",
				GlossaryZoneActive = "Zone aktiv, Bereich, in dem Stehen schadet",
				GlossaryZoneInside = "Zone innen, du stehst in einer Gefahr, weg vom Klang bewegen",
				GlossaryWallTones = "Wandtöne, Wände rechts, links, oben, unten",
				GlossaryWallCollision = "Wandkollision, gegen eine Wand gelaufen",
				GlossaryEnemyPing = "Gegner-Ping, nächster Gegner, antwortet auf die Ortungstaste",
				GlossaryChest = "Truhensignal, hingehen öffnet die Truhe",
				GlossaryExit = "Ausgangssignal, hingehen schließt das Level ab, beendet auch einen Bosskampf",
				PluginLoadedFormat = "Hand of Fate Zugang Version {0} geladen"
			};
		}
	}
}
